apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cassandra-cluster
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cassandra
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: cassandra
    spec:
      containers:
        - image: docker.io/_/cassandra
          #imagePullPolicy: Always
          name: cassandra
          livenessProbe:
            exec:
              command:
                - cqlsh
                - ping
                - -h
                - <ip-adress>
            httpGet:
              path: /admin
              port: 8161
            initialDelaySeconds: 10
            timeoutSeconds: 1
            periodSeconds: 10
            failureThreshold: 3

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: cassandra-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  persistentVolumeReclaimPolicy: Retain
  gcePersistentDisk:
    fsType: ext4
    pdName: apache-fineract-pd

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cassandra-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi