apiVersion: v1
kind: Service
metadata:
  name: customer-service
  namespace: default
spec:
  selector:
    app: customer-ms
  ports:
    - port: 2024
      targetPort: 2024
  type: LoadBalancer

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: customer-ms-cluster
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-ms
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: customer-ms
    spec:
      containers:
      - name: myapp
        image: docker.io/anh3h/customer-ms
        imagePullPolicy: IfNotPresent
        env:
          - name: eureka.instance.hostname
            value: 35.231.169.122
          - name: ribbon.listOfServers
            value: 35.231.169.122:9090
          - name: eureka.client.serviceUrl.defaultZone
            value: http://35.231.169.122:8761/eureka
          - name: activemq.brokerUrl
            value: tcp://35.227.125.206:61616
          - name: cassandra.contactPoints
            value: 35.237.151.82:9042
          - name: mariadb.host
            value: 35.229.63.46
        ports:
          - containerPort: 2024
