apiVersion: v1
kind: Service
metadata:
  name: provisioner-service
  namespace: default
spec:
  selector:
    app: provisioner-ms
  ports:
    - port: 2020
      targetPort: 2020
  type: LoadBalancer

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: provisioner-ms-cluster
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: provisioner-ms
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: provisioner-ms
    spec:
      containers:
      - name: myapp
        image: docker.io/anh3h/provisioner-ms
        imagePullPolicy: IfNotPresent
        env:
          - name: eureka.instance.hostname
            value: 35.196.163.175
          - name: ribbon.listOfServers
            value: 35.196.163.175:9090
          - name: eureka.client.serviceUrl.defaultZone
            value: http://35.196.163.175:8761/eureka
          - name: activemq.brokerUrl
            value: tcp://35.231.130.203:61616
          - name: cassandra.contactPoints
            value: 35.227.125.206:9042
          - name: mariadb.host
            value: 35.237.151.82
        ports:
          - containerPort: 2020
